@extends('layouts.app')
@section('hide-page-title', 'true')
@section('content')
<style>
.lock-hero{background:linear-gradient(120deg,#102b45,#303aa4 75%,#5945d9);border-radius:18px;padding:26px 30px;color:white;display:flex;justify-content:space-between;gap:20px;align-items:center;box-shadow:0 16px 30px #172a5b18}.lock-hero h2{color:white;margin:0 0 5px}.lock-hero p{color:#dbe6f6;margin:0}.lock-stat{background:#ffffff21;border:1px solid #ffffff35;border-radius:12px;padding:12px 18px;min-width:115px;text-align:center}.lock-stat strong{display:block;font-size:24px}.lock-stat small{color:#e0e6fa}.lock-card{border:1px solid #e2e8f2;border-radius:15px;background:white;padding:20px;height:100%;box-shadow:0 6px 18px #172a5b0a}.lock-card h4{font-size:17px;margin:0 0 5px}.lock-card p{color:#738198;font-size:12px}.lock-icon{width:43px;height:43px;border-radius:12px;background:#eeeaff;color:#5b47db;display:grid;place-items:center;font-size:22px}.lock-pill{display:inline-block;border-radius:99px;padding:5px 9px;background:#e7f7f0;color:#16855b;font-size:11px;font-weight:700}.lock-pill.off{background:#fff1eb;color:#c86b32}.lock-row{display:grid;grid-template-columns:44px minmax(0,1fr) auto;gap:13px;align-items:center;padding:14px 0;border-bottom:1px solid #edf0f5}.lock-row:last-child{border-bottom:0}.lock-row strong{display:block}.lock-row small{color:#768399}.lock-field{min-height:43px}.lock-note{background:#f3f7fd;border:1px solid #dce7f6;border-radius:11px;padding:13px;color:#506480;font-size:12px}
@media(max-width:700px){.lock-hero{flex-direction:column;align-items:flex-start;padding:20px}.lock-hero>div:last-child{display:flex;width:100%;gap:8px}.lock-stat{flex:1;min-width:0}.lock-row{grid-template-columns:40px minmax(0,1fr)}.lock-row form{grid-column:1/-1}}
</style>
<div class="lock-hero mb-4"><div><div class="small text-uppercase mb-2" style="letter-spacing:1.3px;color:#c7d8f9">Pattern VH · TTLock</div><h2>Smart Lock Control</h2><p>Sync devices, link each lock to its unit, and issue paid-period guest access.</p></div><div class="d-flex gap-2"><div class="lock-stat"><strong>{{ $locks->count() }}</strong><small>Synced locks</small></div><div class="lock-stat"><strong>{{ $locks->filter(fn($lock)=>$lock->property)->count() }}</strong><small>Linked units</small></div></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-3"><div class="col-lg-4"><div class="lock-card"><h4><i class="ri-links-line me-1 text-primary"></i> Connection</h4><p>Use the TTLock application ID, secret and access token for the account that owns the locks. Secrets are encrypted in HHMS.</p><span class="lock-pill {{ $configured ? '' : 'off' }}">{{ $configured ? 'Configured' : 'Not connected' }}</span>
<form method="POST" action="{{ route('admin.smartlocks.connection') }}" class="mt-3">@csrf<div class="mb-3"><label class="form-label">Client ID</label><input name="client_id" class="form-control lock-field" value="{{ old('client_id',$clientId) }}" autocomplete="off" required></div><div class="mb-3"><label class="form-label">Client secret</label><input type="password" name="client_secret" class="form-control lock-field" placeholder="{{ $configured ? 'Leave blank to keep saved secret' : 'Enter TTLock client secret' }}" autocomplete="new-password"></div><div class="mb-3"><label class="form-label">Access token</label><input type="password" name="access_token" class="form-control lock-field" placeholder="{{ $configured ? 'Leave blank to keep saved token' : 'Enter account access token' }}" autocomplete="new-password"></div><button class="btn btn-primary w-100">Save connection</button></form><div class="lock-note mt-3"><i class="ri-shield-check-line me-1"></i> Do not enter the TTLock master passcode or guest codes here. Existing credentials are never displayed.</div></div></div>
<div class="col-lg-8"><div class="lock-card"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h4>Device inventory</h4><p class="mb-0">Locks fetched from the connected TTLock account. Assign a lock to one unit only.</p></div><form method="POST" action="{{ route('admin.smartlocks.sync') }}">@csrf<button class="btn btn-primary" @disabled(!$configured)><i class="ri-refresh-line me-1"></i>Sync locks</button></form></div><div class="mt-3">@forelse($locks as $lock)<div class="lock-row"><div class="lock-icon"><i class="ri-door-lock-line"></i></div><div><strong>{{ $lock->alias ?: $lock->name }}</strong><small>ID {{ $lock->remote_id }} · Battery {{ $lock->battery === null ? '—' : $lock->battery.'%' }} · V{{ $lock->passcode_version ?? '—' }} passcode · {{ $lock->has_gateway ? 'Gateway connected' : 'No gateway' }}</small>@if($lock->last_synced_at)<small class="d-block">Last synced {{ $lock->last_synced_at->format('d M Y H:i') }}</small>@endif</div><span class="lock-pill {{ $lock->property ? '' : 'off' }}">{{ $lock->property ? ($lock->property->building?->building_name ? $lock->property->building->building_name.' · ' : '').$lock->property->name : 'Unassigned' }}</span></div>@empty<div class="text-center py-5 text-muted"><i class="ri-door-lock-line fs-32 d-block mb-2"></i>No locks synced yet. Save the connection, then select Sync locks.</div>@endforelse</div></div></div></div>
<div class="lock-note mt-3">Guest codes are issued from the booking page, separately for each fully paid invoice period. TTLock remote code creation requires a compatible V4 lock and gateway. An unpaid or legacy-settled invoice cannot issue a code.</div>
@endsection
