<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;background:#edf2f7;font-family:Arial,sans-serif;color:#14253d">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:24px 12px"><tr><td align="center">
<table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;width:100%;background:#fff;border-radius:16px;overflow:hidden">
<tr><td style="background:#092b4e;padding:28px;color:#fff"><img src="{{ asset('assets/images/pattern-bilingual-logo.png') }}" width="210" alt="PATTERN Vacation Homes Rental" style="display:block;max-width:70%;height:auto;background:#fff;border-radius:8px;padding:7px"><p style="margin:22px 0 6px;color:#dfbe77;font-size:12px;letter-spacing:1px">STAY REMINDER</p><h1 style="margin:0;font-size:24px">Checkout is in 3 days</h1></td></tr>
<tr><td style="padding:28px"><p>Hello {{ $booking->guest_name }},</p><p style="line-height:1.6">Your booking <strong>{{ $booking->booking_reference }}</strong> for <strong>{{ $booking->property?->name ?? 'your unit' }}{{ $booking->property?->building?->building_name ? ' — '.$booking->property->building->building_name : '' }}</strong> is scheduled to end on <strong>{{ $booking->check_out?->format('d M Y') }}</strong>.</p>
<p style="line-height:1.6">If you would like to extend, please contact PATTERN before your scheduled checkout. We cannot guarantee an extension if we do not hear from you in time. An extension is subject to availability and is not confirmed until our team creates the new invoice and confirms your booking. Otherwise, please confirm your checkout time.</p>
@if($balanceDue > 0)<div style="background:#fff5e7;border:1px solid #f0d7ad;padding:15px;border-radius:10px;margin:20px 0"><strong>Unpaid invoice balance: AED {{ number_format($balanceDue, 2) }}</strong><br><small>Please review your outstanding invoice(s) in the guest portal or contact our team. This is not a new charge.</small></div>@else<div style="background:#eaf8ef;padding:15px;border-radius:10px;margin:20px 0">No unpaid invoice balance is showing for this booking.</div>@endif
<p style="margin:24px 0"><a href="{{ route('tenant.booking.show', $booking) }}" style="background:#6146d9;color:#fff;text-decoration:none;padding:13px 20px;border-radius:8px;display:inline-block">View booking and invoices</a></p><p style="color:#657184;font-size:13px">If you cannot access the guest portal, reply to this email or contact our office.</p></td></tr>
<tr><td style="padding:16px 28px;background:#f5f7fa;color:#697588;font-size:12px">PATTERN Vacation Homes Rental · Automated booking reminder</td></tr>
</table></td></tr></table></body></html>
